---
- hosts: infra
  vars_files: 
  gather_facts: no
  become: true
  serial: 4
  tasks:     
    - name: Deploy the openshift cluster on VMware environment
      unarchive:
        src: https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/crc-linux-amd64.tar.xz
        dest: /root/
        remote_src: yes
        mode: 0644
        validate_certs: no 